---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "latest"

inputs:
- name: attendee-service-source

run:
  path: attendee-service-source/ci/tasks/blue-green-cleanup.sh